### ISSUE TITLE
Need more detailed instruction on modules install and use

### ISSUE THREAD

**Issue by 42point** [gethugothemes/hugo-modules#16]
I made everything according instruction about adding gallery, and have imported the module.

```bash
hugo mod graph
github.com/42point/newBlog github.com/gethugothemes/hugo-modules/gallery-slider@v0.0.0-20230823074046-d7ebb75df8b9
github.com/42point/newBlog PaperMod
```

But, I didn't get `glightbox.js` or `glightbox.css` files in `static` folder of my project. Do I need to clone them from the repository?

How does it work?

I use YAML format for the config file

```
Params:
  plugins:
    css:
      - link: plugins/glightbox/glightbox.css
    js:
      - link: plugins/glightbox/glightbox.js
      - link: js/gallery-slider.js
   ```

thanks in advance.
